apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app
        image: aldry1303/argocdlab:1.0.0
        ports:
        - containerPort: 80